import = ["/Users/jakobberggren/.config/alacritty/themes/custom/snake.toml"]
live_config_reload = true

[cursor]
blink_timeout = 0
unfocused_hollow = false

[cursor.style]
blinking = "Always"
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]

size = 15.0

[font.normal]
family = "SFMono Nerd Font"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "buttonless"
opacity = 0.9

[window.padding]
x = 10
y = 13
